# Generated by Django 4.1.4 on 2022-12-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_coordinate_lat_alter_coordinate_long'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_id', models.IntegerField()),
                ('name_ar', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('lat', models.DecimalField(decimal_places=8, max_digits=11)),
                ('long', models.DecimalField(decimal_places=8, max_digits=11)),
            ],
        ),
    ]
